export function getRandomWord() {
const words = [
  "firewall", "backyard", "sidekick", "grainery", "daylight", "notebook", "bluebird",
  "handyman", "moonlight", "redesign", "snowfall", "playmate", "keyboard", "lighthouse",
  "algorithm", "sandboxed", "cupboard", "pineapple", "bracelets", "footprint", "material",
  "nightmare", "starving", "umbrella", "vacation", "wildfire", "zeppelin", "birthdays",
  "breaking", "briefcase", "building", "calculator", "campaign", "candidate", "carpenter",
  "cellphone", "challenge", "champion", "character", "chemistry", "childhood", "civilian",
  "clarinet", "classroom", "commander", "commerce", "commuting", "component",
  "computer", "concrete", "conflict", "congress", "contract", "controller",
  "convention", "conversion", "cooking", "corporate", "corridor", "countries", "covering",
  "creation", "creative", "creditor", "criminal", "criteria", "critical", "crossing",
  "customer", "database", "daughter", "deadline", "decision", "delivery", "describe",
  "designer", "detailed", "dialogue", "diameter", "director", "disaster", "discount",
  "discover", "disorder", "distance", "distinct", "document", "dominate", "dramatic",
  "drawing", "dressing", "duration", "dynamics", "earnings", "economic", "educated",
  "electric", "employee", "employer", "endeavor", "engineer", "enormous", "entirely",
  "estimate", "evaluate", "everyone", "evidence", "exchange", "exciting", "exercise",
  "existing", "explicit", "external", "facility", "favorite", "fighting", "flexible",
  "floating", "football", "forecast", "friendly", "function", "generate", "governor",
  "graduate", "graphics", "greatest", "guardian", "guidance", "handling", "hardware",
  "headline", "heritage", "historic", "hospital", "humanity", "important", "instance",
  "internal", "interval", "introduce", "invasion", "involve", "journal", "judgment",
  "landscape", "language", "laughter", "learning", "lifeline", "magnetic", "maintain",
  "majority", "medieval", "movement", "musician", "natural", "negative", "occasion",
  "offering", "ongoing", "operator", "original", "painting", "parallel", "patient",
  "pattern", "penalty", "percent", "perfect", "perform", "perhaps", "physical",
  "planning", "popular", "portion", "previous", "primary", "privacy", "private",
  "problem", "produce", "program", "promise", "promote", "protect", "provide",
  "purpose", "quality", "quantity", "quarter", "quickly", "reading", "reality",
  "receipt", "receive", "record", "reflect", "regional", "regular", "relation",
  "release", "remains", "removal", "replace", "request", "require", "research",
  "resist", "resource", "respect", "response", "result", "returned", "revenue",
  "scenario", "science", "section", "security", "selling", "service", "setting",
  "several", "similar", "situation", "society", "soldier", "solution", "speaker",
  "special", "species", "spending", "station", "storage", "strategy", "student",
  "subject", "success", "suggest", "support", "suppose", "survive", "teacher",
  "technology", "terminal", "territory", "theory", "therapy", "thinking", "thirteen",
  "thousand", "through", "tonight", "toolbox", "tourist", "trained", "transfer",
  "transport", "travel", "treatment", "triangle", "tropical", "uniform", "unknown",
  "unusual", "upgrade", "usually", "utility", "valuable", "variable", "vehicle",
  "village", "violence", "virtual", "walking", "warning", "wedding", "weekend",
  "welcome", "western", "willing", "winning", "without", "writing", "younger",
  "zoologist"
];

const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];}